-- ============================================================
-- InfraDesk Kernel v1
-- PostgreSQL / Flyway migration
--
-- Stable business entities -> relational tables
-- Infrastructure objects    -> generic Resource model
-- Tenant isolation          -> organization_id + composite FKs
--
-- UUID values are generated by the application.
-- ============================================================


-- ============================================================
-- 1. ORGANIZATION
-- ============================================================

CREATE TABLE organization (
                              id          uuid         PRIMARY KEY,
                              code        varchar(64)  NOT NULL,
                              name        varchar(255) NOT NULL,
                              is_active   boolean      NOT NULL DEFAULT true,
                              created_at  timestamptz  NOT NULL DEFAULT now(),
                              updated_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_organization_code_ci
    ON organization (lower(code));


-- ============================================================
-- 2. EMPLOYEE
-- ============================================================

CREATE TABLE employee (
                          id               uuid         PRIMARY KEY,
                          organization_id  uuid         NOT NULL,
                          email            varchar(320) NOT NULL,
                          display_name     varchar(255) NOT NULL,
                          position         varchar(255),
                          is_active        boolean      NOT NULL DEFAULT true,
                          created_at       timestamptz  NOT NULL DEFAULT now(),
                          updated_at       timestamptz  NOT NULL DEFAULT now(),

                          CONSTRAINT fk_employee_organization
                              FOREIGN KEY (organization_id)
                                  REFERENCES organization(id)
);

CREATE UNIQUE INDEX ux_employee_org_email_ci
    ON employee (
                 organization_id,
                 lower(email)
        );

CREATE INDEX ix_employee_organization
    ON employee (organization_id);


-- ============================================================
-- 3. PROJECT
-- ============================================================

CREATE TABLE project (
                         id               uuid         PRIMARY KEY,
                         organization_id  uuid         NOT NULL,
                         code             varchar(64)  NOT NULL,
                         name             varchar(255) NOT NULL,
                         description      text,
                         is_active        boolean      NOT NULL DEFAULT true,
                         created_at       timestamptz  NOT NULL DEFAULT now(),
                         updated_at       timestamptz  NOT NULL DEFAULT now(),

                         CONSTRAINT fk_project_organization
                             FOREIGN KEY (organization_id)
                                 REFERENCES organization(id),

    -- Needed as target for tenant-aware foreign keys.
                         CONSTRAINT uq_project_id_organization
                             UNIQUE (id, organization_id)
);

CREATE UNIQUE INDEX ux_project_org_code_ci
    ON project (
                organization_id,
                lower(code)
        );

CREATE INDEX ix_project_organization
    ON project (organization_id);


-- ============================================================
-- 4. ENVIRONMENT
-- ============================================================

CREATE TABLE environment (
                             id               uuid         PRIMARY KEY,
                             organization_id  uuid         NOT NULL,
                             project_id       uuid         NOT NULL,
                             code             varchar(64)  NOT NULL,
                             name             varchar(255) NOT NULL,
                             kind             varchar(32)  NOT NULL,
                             is_active        boolean      NOT NULL DEFAULT true,
                             created_at       timestamptz  NOT NULL DEFAULT now(),
                             updated_at       timestamptz  NOT NULL DEFAULT now(),

                             CONSTRAINT ck_environment_kind
                                 CHECK (
                                     kind IN (
                                              'DEV',
                                              'TEST',
                                              'STAGE',
                                              'PROD',
                                              'CUSTOM'
                                         )
                                     ),

                             CONSTRAINT fk_environment_project_tenant
                                 FOREIGN KEY (
                                              project_id,
                                              organization_id
                                     )
                                     REFERENCES project (
                                                         id,
                                                         organization_id
                                         ),

                             CONSTRAINT uq_environment_id_organization
                                 UNIQUE (
                                         id,
                                         organization_id
                                     ),

                             CONSTRAINT uq_environment_id_project_organization
                                 UNIQUE (
                                         id,
                                         project_id,
                                         organization_id
                                     )
);

CREATE UNIQUE INDEX ux_environment_project_code_ci
    ON environment (
                    organization_id,
                    project_id,
                    lower(code)
        );

CREATE INDEX ix_environment_project
    ON environment (
                    organization_id,
                    project_id
        );


-- ============================================================
-- 5. RESOURCE TYPE
-- ============================================================
--
-- Platform-wide infrastructure types.
--
-- Business/runtime implementation lives in Scala:
--
-- NODE -> NodeDefinition
--         NodeSpec
--         NodeStatus
--
-- resource_type contains metadata, not another copy of the
-- Scala schema.
-- ============================================================

CREATE TABLE resource_type (
                               id              uuid         PRIMARY KEY,
                               code            varchar(64)  NOT NULL,
                               name            varchar(255) NOT NULL,
                               schema_version  integer      NOT NULL DEFAULT 1,
                               capabilities    text[]       NOT NULL DEFAULT ARRAY[]::text[],
                               is_active       boolean      NOT NULL DEFAULT true,
                               created_at      timestamptz  NOT NULL DEFAULT now(),
                               updated_at      timestamptz  NOT NULL DEFAULT now(),

                               CONSTRAINT ck_resource_type_schema_version
                                   CHECK (schema_version > 0)
);

CREATE UNIQUE INDEX ux_resource_type_code_ci
    ON resource_type (lower(code));


-- ============================================================
-- System resource types
-- ============================================================

INSERT INTO resource_type (
    id,
    code,
    name,
    schema_version,
    capabilities
)
VALUES (
           '10000000-0000-0000-0000-000000000001',
           'NODE',
           'Node',
           1,
           ARRAY[
               'HEALTH_CHECK',
               'METRICS'
               ]::text[]
       );


-- ============================================================
-- 6. RESOURCE
-- ============================================================
--
-- Generic infrastructure object.
--
-- Examples:
-- NODE
-- SERVICE
-- DOMAIN
-- CERTIFICATE
-- POSTGRESQL
-- DOCKER_CONTAINER
--
-- spec:
--     durable/type-specific resource data
--
-- status:
--     latest observed runtime state
--
-- Resource always belongs to an Environment in v1.
-- ============================================================

CREATE TABLE resource (
                          id                  uuid         PRIMARY KEY,
                          organization_id     uuid         NOT NULL,
                          environment_id      uuid         NOT NULL,
                          resource_type_id    uuid         NOT NULL,
                          parent_resource_id  uuid,
                          code                varchar(128) NOT NULL,
                          name                varchar(255) NOT NULL,

                          spec                 jsonb        NOT NULL DEFAULT '{}'::jsonb,
                          status               jsonb        NOT NULL DEFAULT '{}'::jsonb,

                          is_active            boolean      NOT NULL DEFAULT true,
                          created_at           timestamptz  NOT NULL DEFAULT now(),
                          updated_at           timestamptz  NOT NULL DEFAULT now(),

                          CONSTRAINT fk_resource_environment_tenant
                              FOREIGN KEY (
                                           environment_id,
                                           organization_id
                                  )
                                  REFERENCES environment (
                                                          id,
                                                          organization_id
                                      ),

                          CONSTRAINT fk_resource_type
                              FOREIGN KEY (resource_type_id)
                                  REFERENCES resource_type(id),

                          CONSTRAINT ck_resource_not_own_parent
                              CHECK (
                                  parent_resource_id IS NULL
                                      OR parent_resource_id <> id
                                  ),

                          CONSTRAINT uq_resource_id_organization
                              UNIQUE (
                                      id,
                                      organization_id
                                  ),

    -- Needed for parent-resource tenant/environment validation.
                          CONSTRAINT uq_resource_id_org_environment
                              UNIQUE (
                                      id,
                                      organization_id,
                                      environment_id
                                  ),

                          CONSTRAINT fk_resource_parent_same_environment
                              FOREIGN KEY (
                                           parent_resource_id,
                                           organization_id,
                                           environment_id
                                  )
                                  REFERENCES resource (
                                                       id,
                                                       organization_id,
                                                       environment_id
                                      )
);


-- Top-level resources.
--
-- Different ResourceTypes may use the same code:
--
-- NODE     / backend
-- SERVICE  / backend

CREATE UNIQUE INDEX ux_resource_root_code_ci
    ON resource (
                 organization_id,
                 environment_id,
                 resource_type_id,
                 lower(code)
        )
    WHERE parent_resource_id IS NULL;


-- Child resources.
--
-- Example:
--
-- node-1
--   └── nginx
--
-- node-2
--   └── nginx
--
-- Both nginx resources are allowed because parents differ.

CREATE UNIQUE INDEX ux_resource_child_code_ci
    ON resource (
                 organization_id,
                 parent_resource_id,
                 resource_type_id,
                 lower(code)
        )
    WHERE parent_resource_id IS NOT NULL;


CREATE INDEX ix_resource_environment
    ON resource (
                 organization_id,
                 environment_id
        );

CREATE INDEX ix_resource_parent
    ON resource (
                 organization_id,
                 parent_resource_id
        );

CREATE INDEX ix_resource_type
    ON resource (resource_type_id);


-- ============================================================
-- 7. RESOURCE RELATION
-- ============================================================
--
-- parent_resource_id:
--     containment / structural hierarchy
--
-- resource_relation:
--     semantic relationships
--
-- Examples:
--
-- USES
-- DEPENDS_ON
-- PROXIES_TO
-- POINTS_TO
-- SECURES
-- ============================================================

CREATE TABLE resource_relation (
                                   id                 uuid        PRIMARY KEY,
                                   organization_id    uuid        NOT NULL,
                                   from_resource_id   uuid        NOT NULL,
                                   relation_type      varchar(64) NOT NULL,
                                   to_resource_id     uuid        NOT NULL,
                                   metadata           jsonb       NOT NULL DEFAULT '{}'::jsonb,
                                   created_at         timestamptz NOT NULL DEFAULT now(),

                                   CONSTRAINT ck_resource_relation_not_self
                                       CHECK (
                                           from_resource_id <> to_resource_id
                                           ),

                                   CONSTRAINT fk_resource_relation_from_tenant
                                       FOREIGN KEY (
                                                    from_resource_id,
                                                    organization_id
                                           )
                                           REFERENCES resource (
                                                                id,
                                                                organization_id
                                               ),

                                   CONSTRAINT fk_resource_relation_to_tenant
                                       FOREIGN KEY (
                                                    to_resource_id,
                                                    organization_id
                                           )
                                           REFERENCES resource (
                                                                id,
                                                                organization_id
                                               ),

                                   CONSTRAINT uq_resource_relation
                                       UNIQUE (
                                               organization_id,
                                               from_resource_id,
                                               relation_type,
                                               to_resource_id
                                           )
);

CREATE INDEX ix_resource_relation_from
    ON resource_relation (
                          organization_id,
                          from_resource_id
        );

CREATE INDEX ix_resource_relation_to
    ON resource_relation (
                          organization_id,
                          to_resource_id
        );


-- ============================================================
-- 8. CONNECTION
-- ============================================================
--
-- Long-lived external-system configuration.
--
-- Examples:
--
-- Docker PROD
-- GitHub
-- Prometheus
-- Selectel
-- Agent
--
-- Scope:
--
-- ORGANIZATION
-- PROJECT
-- ENVIRONMENT
-- ============================================================

CREATE TABLE connection (
                            id               uuid         PRIMARY KEY,
                            organization_id  uuid         NOT NULL,

                            scope_type       varchar(32)  NOT NULL,
                            project_id       uuid,
                            environment_id   uuid,

                            connector_type   varchar(64)  NOT NULL,
                            code             varchar(64)  NOT NULL,
                            name             varchar(255) NOT NULL,

                            config            jsonb        NOT NULL DEFAULT '{}'::jsonb,
                            secret_ref        varchar(255),

                            is_active         boolean      NOT NULL DEFAULT true,
                            created_at        timestamptz  NOT NULL DEFAULT now(),
                            updated_at        timestamptz  NOT NULL DEFAULT now(),

                            CONSTRAINT fk_connection_organization
                                FOREIGN KEY (organization_id)
                                    REFERENCES organization(id),

                            CONSTRAINT fk_connection_project_tenant
                                FOREIGN KEY (
                                             project_id,
                                             organization_id
                                    )
                                    REFERENCES project (
                                                        id,
                                                        organization_id
                                        ),

                            CONSTRAINT fk_connection_environment_tenant
                                FOREIGN KEY (
                                             environment_id,
                                             project_id,
                                             organization_id
                                    )
                                    REFERENCES environment (
                                                            id,
                                                            project_id,
                                                            organization_id
                                        ),

                            CONSTRAINT ck_connection_scope
                                CHECK (
                                    (
                                        scope_type = 'ORGANIZATION'
                                            AND project_id IS NULL
                                            AND environment_id IS NULL
                                        )
                                        OR
                                    (
                                        scope_type = 'PROJECT'
                                            AND project_id IS NOT NULL
                                            AND environment_id IS NULL
                                        )
                                        OR
                                    (
                                        scope_type = 'ENVIRONMENT'
                                            AND project_id IS NOT NULL
                                            AND environment_id IS NOT NULL
                                        )
                                    ),

                            CONSTRAINT uq_connection_id_organization
                                UNIQUE (
                                        id,
                                        organization_id
                                    )
);

CREATE UNIQUE INDEX ux_connection_org_code_ci
    ON connection (
                   organization_id,
                   lower(code)
        );

CREATE INDEX ix_connection_project
    ON connection (
                   organization_id,
                   project_id
        )
    WHERE project_id IS NOT NULL;

CREATE INDEX ix_connection_environment
    ON connection (
                   organization_id,
                   environment_id
        )
    WHERE environment_id IS NOT NULL;


-- ============================================================
-- 9. EXTERNAL REF
-- ============================================================
--
-- Stable external identity mapping.
--
-- Example:
--
-- connection:
--     Docker PROD
--
-- external_type:
--     container
--
-- external_id:
--     Docker container ID
--
-- resource_id:
--     InfraDesk UUID
-- ============================================================

CREATE TABLE external_ref (
                              id               uuid         PRIMARY KEY,
                              organization_id  uuid         NOT NULL,
                              connection_id    uuid         NOT NULL,

                              external_type    varchar(64)  NOT NULL,
                              external_id      varchar(512) NOT NULL,

                              resource_id      uuid         NOT NULL,

                              first_seen_at    timestamptz  NOT NULL DEFAULT now(),
                              last_seen_at     timestamptz  NOT NULL DEFAULT now(),

                              created_at       timestamptz  NOT NULL DEFAULT now(),
                              updated_at       timestamptz  NOT NULL DEFAULT now(),

                              CONSTRAINT fk_external_ref_connection_tenant
                                  FOREIGN KEY (
                                               connection_id,
                                               organization_id
                                      )
                                      REFERENCES connection (
                                                             id,
                                                             organization_id
                                          ),

                              CONSTRAINT fk_external_ref_resource_tenant
                                  FOREIGN KEY (
                                               resource_id,
                                               organization_id
                                      )
                                      REFERENCES resource (
                                                           id,
                                                           organization_id
                                          ),

                              CONSTRAINT uq_external_ref_identity
                                  UNIQUE (
                                          connection_id,
                                          external_type,
                                          external_id
                                      )
);

CREATE INDEX ix_external_ref_resource
    ON external_ref (
                     organization_id,
                     resource_id
        );

CREATE INDEX ix_external_ref_last_seen
    ON external_ref (
                     connection_id,
                     last_seen_at
        );